[package]
name = "bb8-mongodb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.56"
bb8 = "0.8.0"
mongodb = "2.3.0"
thiserror = "1.0.31"
