[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
categories = ["asynchronous", "database"]
description = "bb8 connection pooling impmentation for the MongoDB database"
documentation = "http://docs.rs/bb8-mongodb"
edition = "2021"
homepage = "http://github.com/rustyhorde/bb8-mongodb"
keywords = ["bb8", "async", "mongodb", "pool"]
license = "MIT OR Apache-2.0"
name = "bb8-mongodb"
readme = "README.md"
repository = "https://github.com/rustyhorde/bb8-mongodb"
version = "0.2.0"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.58"
bb8 = "0.8.0"
mongodb = "2.3.1"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["full"] }
